name: Rosey the Robot
on: [push, pull_request, release]
jobs:

  build:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Requirements and Dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install -e .[test]
